name: Bamboo-Plung-2222022V2.3-DEV_BETA
version: 1.0-SNAPSHOT
main: bamboplugin.bamboplugin.BamboPlugin
api-version: 1.18
commands:
  glasshelm:
    description: spawns glasshelm
    usage: /<command>
  give_all_glasshelms:
    description: gives all glass helm colors
    usage: /<command>
  ben:
    description: gives user ben
    usage: /<command>